development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://fitfriender.herokuapp.com"
  secret_token: "7ecc57c522c8ee6a3a31838e3f0e2455adb20fdec63a2a7852aa1761f9daecab"
  signature_expiration: 3600 # one hour
